# Generated by Django 2.0.3 on 2018-04-23 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('nome_social', models.CharField(blank=True, max_length=80, null=True)),
                ('aliado', models.CharField(choices=[('sim', 'SIM'), ('nao', 'NÃO')], default='nao', max_length=3)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=10, verbose_name='RG')),
                ('rg_uf', models.IntegerField(blank=True, null=True, verbose_name='RG / UF')),
                ('titulo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Título')),
                ('titulo_secao', models.CharField(blank=True, max_length=6, null=True, verbose_name='Seção')),
                ('titulo_zona', models.CharField(blank=True, max_length=6, null=True, verbose_name='Zona')),
                ('titulo_uf', models.IntegerField(blank=True, null=True, verbose_name='Título / Município')),
                ('data_nascimento', models.DateField(verbose_name='Aniversário')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('estado_civil', models.CharField(choices=[('Casado', 'Casado(a)'), ('Solteiro', 'Solteiro(a)'), ('Outros', 'Outros')], default='Solteiro', max_length=8, verbose_name='Estado civil')),
                ('naturalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('escolaridade', models.CharField(blank=True, choices=[('efc', 'Ensino Fundamental Completo'), ('efi', 'Ensino Fundamental Incompleto'), ('emc', 'Ensino Médio Completo'), ('emi', 'Ensino Médio Incompleto'), ('ctc', 'Curso Técnico Completo'), ('cti', 'Curso Técnico Incompleto'), ('nsc', 'Curso Superior Completo'), ('nsi', 'Curso Superior Incompleto'), ('mes', 'Mestrado'), ('dr', 'Doutorado'), ('phd', 'Pós-Doutorado')], max_length=3, null=True)),
                ('profissao', models.CharField(blank=True, max_length=80, null=True, verbose_name='Profissão')),
                ('nome_da_mae', models.CharField(max_length=80, verbose_name='Nome da Mãe')),
                ('nome_do_pai', models.CharField(blank=True, max_length=80, null=True)),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('cep', models.CharField(blank=True, max_length=14, null=True, verbose_name='CEP')),
                ('email', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('telefone_celular', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone Celular')),
                ('telefone_residencial', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telenone Residencial')),
                ('telefone_trabalho', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone do Trabalho')),
                ('indicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sic.Pessoa')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'db_table': 'pessoas',
                'verbose_name_plural': 'Pessoas',
            },
        ),
    ]
