# Generated by Django 2.0.3 on 2018-04-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nome_da_mae',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='rg',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='RG'),
        ),
    ]
