# Generated by Django 2.0.3 on 2018-05-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sic', '0002_auto_20180423_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Bairros',
                'db_table': 'bairros',
                'verbose_name': 'Bairro',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Cidades',
                'db_table': 'cidades',
                'verbose_name': 'Cidade',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sigla', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
                'verbose_name': 'Estado',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('estado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sic.Estado')),
            ],
            options={
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipios',
                'verbose_name': 'Municipio',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('codigo', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'db_table': 'paises',
                'verbose_name': 'Pais',
            },
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='titulo',
            new_name='titulo_eleitor',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Nasc.'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='estado_civil',
            field=models.CharField(choices=[('Casado(a)', 'Casado(a)'), ('Solteiro(a)', 'Solteiro(a)'), ('Outros', 'Outros')], default='Solteiro', max_length=12, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=10),
        ),
        migrations.AddField(
            model_name='estado',
            name='pais_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sic.Pais'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='municipio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sic.Municipio'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='cidade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sic.Cidade'),
        ),
    ]
