# Generated by Django 2.0.3 on 2018-05-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sic', '0003_auto_20180513_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
