# Generated by Django 2.0.3 on 2018-05-15 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sic', '0008_auto_20180515_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cidade_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sic.Cidade'),
        ),
    ]
