# Generated by Django 2.0.3 on 2018-05-15 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sic', '0009_pessoa_cidade_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='bairro_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sic.Bairro'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='estado_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sic.Estado'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='profissao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sic.Profissao'),
        ),
    ]
